//
//  Champions.swift
//  ADCarries
//
//  Created by İbrahim Ballıbaba on 17.09.2022.
//

import Foundation
import UIKit

struct Marksman {
    var champName: String
    var champImage: UIImage
    var champInfo: String
    
    struct ChampionsData {
        
        static let characterData = [Marksman(champName: "Aphelios", champImage: UIImage(named: "Aphelios0")!, champInfo: "Ellerinde silahlarıyla ay ışığının gölgelerinden beliren Aphelios, inancına düşman olanları kasvetli bir sessizlik içinde ortadan kaldırır. Kendisini sadece keskin nişancılığı ve silahlarının sesiyle ifade eder. Onu dilsiz kılan bir zehirden güç almasına rağmen, kız kardeşi Alune ona yol gösterir. Uzaklardaki tapınağından, kardeşinin ellerinde ay taşından yapılma pek çok silahın ortaya çıkmasını sağlar. Ay gökte olduğu sürece Aphelios yalnız kalmayacak."),
                      Marksman(champName: "Ashe", champImage: UIImage(named: "Ashe0")!, champInfo: "Avarosa Kabilesi'nin Buzdoğan savaş anası Ashe, kuzeyin en kalabalık güruhuna komutanlık ediyor. Metanetli, zeki, idealist ama liderlik vazifesinden de bir o kadar rahatsız olan Ayaz Okçu, soyunun atadan kalma büyülerini kullanarak Gerçek Buz'dan bir yaya hükmediyor. Halkının onun efsanevi savaşçı Avarosa'nın yeniden doğmuş hali olduğuna dair inancını arkasına alan Ashe, kadim kabile topraklarını yeniden ele geçirerek Freljord'u bir kez daha birleştirmeyi umut ediyor."),
                      Marksman(champName: "Caitlyn", champImage: UIImage(named: "Caitlyn0")!, champInfo: "Barış gücünün en iyisi sayılan Caitlyn, Piltover'ın en iyi nişancısı olarak şehri kurnaz suçlulardan arındırma konusunda rakip tanımıyor. Genellikle Vi ile birlikte göreve çıkıp ortağının fevri doğasını dengeliyor. Türünün tek örneği olan bir hextech tüfeği taşısa da Caitlyn'in en güçlü silahı, Gelişim Şehri'nde iş tutacak kadar aptal kanunsuzlara özenle tuzak kurmasını sağlayan üstün zekâsı."),
                      Marksman(champName: "Draven", champImage: UIImage(named: "Draven0")!, champInfo: "Noxus'ta Hükümcüler adıyla anılan savaşçılar, kanın oluk oluk aktığı ve gücün sınandığı arenalarda karşı karşıya gelir ama hiçbiri Draven kadar rağbet görmez. Bu eski savaşçı, seyirci kitlelerinin abartıya olan doğal yeteneğini ve elbette dönen baltalarını kullanmaktaki becerisini büyük takdirle karşıladığını keşfetmiş. Kendi küstah kusursuzluğuna hayran olan Draven, imparatorluğun dört bir yanında sonsuza kadar adına tezahürat edilmesini sağlamak için kimi yenmesi gerekirse yeneceğine ant içmiş."),
                      Marksman(champName: "Ezreal", champImage: UIImage(named: "Ezreal0")!, champInfo: "Gözüpek bir maceracı olan Ezreal, fark etmese de savaş sanatları konusunda çok yetenekli. Bin yıllardır kayıp olan yeraltı mezarlarına dalıyor, kadim lanetlerden kurtuluyor ve aşılması imkânsız görünen zorlukları kolayca aşıyor. Ataklığı ve cesareti sınır tanımıyor. Her sorunun çözümünü doğaçlama olarak bulmayı tercih ediyor. Bu konuda kısmen işlek zekâsına, çoğunlukla da yıkıcı sihir atışları yapabilen Shurima işi büyülü eldivenine güveniyor. Eğer Ezreal yakınlardaysa bela da hemen arkasından gelecektir. Ya da önünden. Muhtemelen her yerden."),
                      Marksman(champName: "Jhin", champImage: UIImage(named: "Jhin0")!, champInfo: "Jhin cinayetin sanat olduğuna inanan, titiz mi titiz, cani bir psikopat. Bir zamanlar Ionia hapishanelerinde çürürken bir anda Ionia'yı yöneten meclisteki karanlık odaklar tarafından serbest bırakılan bu seri katil, şimdilerde kendisini serbest bırakan entrikacılar için suikastlar düzenliyor. Silahına adeta bir fırça gözüyle bakan Jhin, ortaya çıkardığı sanatsal vahşet eserleriyle hem kurbanlarının hem de bu eserleri görenlerin yüreklerine korku salıyor. Tüyler ürperten tiyatrosunu sergilemekten vahşi bir zevk alan Jhin, gelmiş geçmiş en güçlü mesajı vermek için ideal bir tetikçi. Bu mesaj ne mi? Dehşet elbette."),
                      Marksman(champName: "Jinx", champImage: UIImage(named: "Jinx0")!, champInfo: "Kafadan kontak ve aklına eseni yapan Zaun'lu suçlu Jinx, sonuçlarına hiç aldırmadan ortalığı karıştırmak için yaşıyor. Elinin altındaki sayısız ölümcül silahla en büyük gümbürtüleri çıkarıp en parlak patlamalara sebep oluyor ve ardında daima kargaşa ve telaş bırakıyor. Jinx can sıkıntısından tiksiniyor ve adım attığı her yere neşeyle kendi karmaşa ve curcuna imzasını atıyor."),
                      Marksman(champName: "Kai'Sa", champImage: UIImage(named: "Kaisa0")!, champInfo: "Henüz bir çocukken Hiçlik'in pençesine düşen Kai'Sa, sadece iradesinin gücü ve azmi sayesinde hayatta kalmayı başardı. Yaşadıkları onu ölümcül bir avcıya dönüştürürken, bazıları için dünya gözüyle görmek istemeyecekleri bir geleceğin habercisi haline getirdi. Hiçlik'te canlı bir kabukla zor bir ortakyaşama sürüklenmiş Kai'Sa, eninde sonunda ikisinden birini seçmek zorunda kalacak: Onu bir canavar olarak gören ölümlüleri affetmek ve onları bekleyen karanlığı birlikte defetmek ya da her şeyi unutarak Hiçlik'in, kendisini geride bırakan bu dünyayı tüketmesine izin vermek."),
                      Marksman(champName: "Kalista", champImage: UIImage(named: "Kalista0")!, champInfo: "Öç hırsı ve öfkeyle dolu bir varlık olan Kalista, çağırıldığında hain ve hilekârları avlamak için Gölge Adalar'dan çıkıp gelen ölümsüz, intikamcı bir ruh. İhanete uğrayan kişi kanlar içinde feryat ediyor bile olsa, Kalista yalnızca kendisine ruhlarıyla ödeme yapabilecek olanları seçer. Gazabı üzerine çökenlerin vay haline; artık son dualarını etseler iyi olur çünkü bu acımasız avcıyla yapılan anlaşmalar, ancak ve ancak ruh söken, soğuk bir alevle bezeli mızrakların hedefine saplanmasıyla son bulur."),
                      Marksman(champName: "Kog'Maw", champImage: UIImage(named: "KogMaw0")!, champInfo: "Çorak Icathia topraklarının derinliklerinde, çürüyen bir Hiçlik akıntısından çıkagelen Kog'Maw, vıcık vıcık, dipsiz ağzıyla dikkat çeken, meraklı ve bir o kadar da iğrenç bir varlık. Bu kendine has Hiçlik yaratığı, kemirip salyaya boğmadığı hiçbir şeyi anlayamıyor. Özünde kötülük olmasa da Kog'Maw'ın insanı ilk bakışta yanıltan saflığına temkinle yaklaşmak gerekir çünkü bu saflık genellikle karın doyurmak için değil, merakını gidermek için kapıldığı bir yeme çılgınlığının habercisidir."),
                      Marksman(champName: "Lucian", champImage: UIImage(named: "Lucian0")!, champInfo: "Bir zamanlar Işık Muhafızı olan Lucian, şimdi hortlak avcısı. Peşlerine düşüp yakaladığı yerde onları kadim çifte tabancalarıyla yok ediyor. Hortlak Thresh eşini öldürdükten sonra Lucian intikam yoluna baş koydu. Ama eşi yaşayanlar arasına döndüğü halde Lucian'ın hiddetinde eksilme olmadı. Acımasız ve hedefine kilitlenmiş olan Lucian, yaşayanları Kara Sis'in çoktan ölmüş dehşetlerinden koruma yolunda hiçbir engel tanımıyor."),
                      Marksman(champName: "Miss Fortune", champImage: UIImage(named: "MissFortune0")!, champInfo: "Güzelliğiyle gözlere bayram ettiren, acımasızlığıyla yüreklere dehşet salan Bilgewater'lı kaptan Sarah Fortune, yaşadığı liman şehrinin pişkin suçlularıyla tezat bir tablo çiziyor. Çocukluğunda yağmacı kral Gangplank'in ailesini katlettiğine tanık oldu ve yıllar sonra kralın gemisini havaya uçurarak gaddarca intikam almayı bildi. Onu hafife alanların, karşılarında kurnaz ve sağı solu belli olmayan bir hasım... ve muhtemelen karınlarında bir iki kurşun bulacağı kesin."),
                      Marksman(champName: "Samira", champImage: UIImage(named: "Samira0")!, champInfo: "Samira yıkılmaz özgüveniyle ölümün gözlerinin içine bakıyor ve nereye giderse gitsin, her zaman heyecan arıyor. Shurima'daki evi çocukken yıkılan Samira, hayattaki tutkusunu tehlikeli görevleri üstlenerek havalı ve korkusuz bir savaşçı olarak tanındığı Noxus'ta buldu. Kara barut tabancalar ve özel olarak yapılmış bir kılıç kullanan Samira, kendisini ölüm kalım durumlarında bulmaktan zevk duyuyor ve önüne çıkan herkesi gösterişli bir şekilde alt ediyor."),
                      Marksman(champName: "Senna", champImage: UIImage(named: "Senna0")!, champInfo: "Çocukluğunda Kara Sis'in lanetleyip musallat olduğu Senna, Işık Muhafızları adlı kutsal bir birliğe katılarak durumuna karşı koydu. Fakat çabaları ölümle sonuçlandı ve zalim hortlak Thresh onu fenerine hapsetti. Yine de umudunu yitirmeyen Senna, Sis'i kullanmayı öğrendi ve kalıcı olarak değişmiş halde yeni bir yaşama doğdu. Muhafız şimdi hem karanlığın hem aydınlığın gücüne hükmedebiliyor ve Kara Sis'i kendisine karşı kullanarak sonunu getirmeye çalışıyor. Yaptığı her atış, sisin içindeki talihsiz ruhları serbest bırakıyor."),
                      Marksman(champName: "Sivir", champImage: UIImage(named: "Sivir0")!, champInfo: "Sivir, zanaatını Shurima çöllerinde icra eden bir avcı ve paralı asker komutanı. Mücevherlerle kaplı, efsanevi dörtlü bıçağıyla giriştiği nice savaşta, dudak uçuklatan ücretini karşılayabilenler için kazandığı zaferlerin haddi hesabı yok. Hiçbir korkuya boyun eğmeyen azmi ve bitmek bilmez hırsıyla, Shurima'nın tehlikelerle dolu yeraltı mezarlarına gömülü hazinelerinden kaldırdığı büyük ganimetlerle gurur duyuyor. Kadim güçlerin Shurima'nın temellerini sarsmaya başlamasıyla birlikte, Sivir de kendini kader çatışmalarının ortasında buluyor."),
                      Marksman(champName: "Tristana", champImage: UIImage(named: "Tristana0")!, champInfo: "Çoğu yordle enerjisini keşifler, icatlar veya sadece yaramazlık yapmak için kullansa da Tristana hep büyük savaşçıların maceralarında kendine ilham bulmuş biri. Runeterra'nın bölgeleri ve savaşları hakkında duyduğu onca şey, onu kendi türünün de efsane olabileceğini düşünmeye yönlendirmiş. Dış dünyaya ilk defa adım atan Tristana, emektar silahı Topatan ve yıkılmaz cesareti ve iyimserliğiyle birlikte savaşın tam ortasına sıçramaktan geri durmuyor."),
                      Marksman(champName: "Twitch", champImage: UIImage(named: "Twitch0")!, champInfo: "Bir Zaun veba faresi olarak dünyaya gelen ve tutkulu bir pislik erbabı olan Twitch, pençelerini kirletmekten asla çekinmiyor. Kimya ile güçlendirilmiş arbaletini Piltover'ın ışıltılı kalbine doğrultan Veba Getiren, yukarıdaki şehirde yaşayan insanlara aslında ne kadar pis olduklarını göstermeye ant içmiş. O hep saklanmayı tercih eden biri ve Kuyu'da dolaşıp durmadığı zamanlarda diğer insanların çöplerini karıştırarak kıymeti bilinmemiş hazineler veya küflü bir sandviç bulmaya çalışıyor."),
                      Marksman(champName: "Varus", champImage: UIImage(named: "Varus0")!, champInfo: "Kadim darkinlerden biri olan Varus, düşmanlarına işkence etmekten keyif alan ve öldürücü okunu fırlatmadan önce onları delirmenin eşiğine getiren korkunç bir katildi. Büyük Darkin Savaşı bittiğinde hapsedilmesine rağmen yüzyıllar sonra iki Ionia'lı avcının yeniden şekillenen bedenleri sayesinde kaçmayı başardı. Avcılar onu bilmeyerek serbest bırakmış ve lanetlenerek hapsolmuş özünü saklayan yayı taşımak zorunda kalmıştı. Varus artık korkunç intikamını gerçekleştirebilmek için onu tutsak edenleri arıyor; ancak içindeki ölümlü ruhlar her fırsatta direnmekten geri durmuyor."),
                      Marksman(champName: "Vayne", champImage: UIImage(named: "Vayne0")!, champInfo: "Shauna Vayne, hayatını ailesini katleden iblisi bulup yok etmeye adamış ölümcül ve acımasız bir canavar avcısı. Bileklerindeki arbalet ve kalbindeki intikam aşkıyla Vayne, yalnızca gölgelerin içinden fırlattığı gümüş ok salvolarıyla karanlık güçlerin kullanıcılarını ve ortaya çıkardıkları yaratıkları yok ederken gerçek anlamda mutluluk bulabiliyor."),
                      Marksman(champName: "Xayah", champImage: UIImage(named: "Xayah0")!, champInfo: "Xayah, halkını kurtarmak için bireysel savaş veren ölümcül ve kusursuz bir vastaya devrimcisi. Hızını, kurnazlığını ve jilet gibi keskin tüy bıçaklarını kullanarak yoluna çıkan herkesi yok ediyor. Xayah, ortağı ve sevgilisi Rakan ile omuz omuza çarpışarak gitgide küçülen kabilesini korumaya ve ırkını eski ihtişamına kavuşturmaya çalışıyor."),
                      Marksman(champName: "Zeri", champImage: UIImage(named: "Zeri0")!, champInfo: "Zaun'lu işçi sınıfı bir aileden gelme, dikbaşlı ve heyecanlı bir genç kadın olan Zeri, sahip olduğu elektrik büyüsünü yoğunlaştırarak özel yapım silahını dolduruyor. Değişken güçleri duygularını, kıvılcımlarıysa hayata olan yıldırım hızında yaklaşımını yansıtıyor. Herkese büyük bir şefkatle yaklaşan Zeri, her savaşında ailesine ve evine duyduğu sevgiden güç alıyor. Yardım etmeye fazla istekli olması bazen başına dert açsa da, Zeri'nin yürekten inandığı bir gerçek var: Halkının arkasında durursan halkın da senin arkanda durur."),]
    }
}
